# Generated by Django 6.0.4 on 2026-04-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('Panadería', 'Panadería'), ('Pastelería', 'Pastelería'), ('Empanadas', 'Empanadas')], max_length=50)),
                ('precio', models.IntegerField()),
                ('stock', models.IntegerField(default=0)),
                ('imagen', models.ImageField(upload_to='productos/')),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
    ]
