# Generated by Django 6.0.4 on 2026-04-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_producto_descripcion_producto_es_oferta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_anterior',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
