# Generated by Django 6.0.4 on 2026-04-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='metodo_entrega',
            field=models.CharField(choices=[('despacho', 'Despacho a Domicilio'), ('retiro', 'Retiro en Local (Av. Providencia 1234)')], default='despacho', max_length=20),
        ),
    ]
