# Generated by Django 6.0.4 on 2026-04-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_orden_metodo_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='metodo_pago',
            field=models.CharField(choices=[('mercadopago', 'MercadoPago (Online)'), ('presencial', 'Pago en Local')], default='mercadopago', max_length=20),
        ),
    ]
