# Generated by Django 6.0.4 on 2026-04-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_orden_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='entregado',
            field=models.BooleanField(default=False, verbose_name='Entregado'),
        ),
    ]
