# Generated by Django 6.0.4 on 2026-04-09 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_orden_entregado'),
    ]

    operations = [
        migrations.CreateModel(
            name='GananciaDiaria',
            fields=[
            ],
            options={
                'verbose_name': 'Ganancia Diaria',
                'verbose_name_plural': 'Reporte de Ganancias',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.orden',),
        ),
    ]
