# Generated by Django 6.0.4 on 2026-04-09 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_gananciadiaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='carrito_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
