# Generated by Django 6.0.4 on 2026-04-09 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_orden_carrito_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='GananciaMensual',
            fields=[
            ],
            options={
                'verbose_name': 'Ganancia Mensual',
                'verbose_name_plural': 'Reporte Mensual',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.orden',),
        ),
    ]
