# Generated by Django 6.0.4 on 2026-04-09 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_gananciamensual'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='hora_retiro',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de Retiro'),
        ),
    ]
