# Generated by Django 6.0.4 on 2026-04-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_resena'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resena',
            options={'verbose_name': 'Reseña', 'verbose_name_plural': 'Reseñas'},
        ),
        migrations.AlterField(
            model_name='resena',
            name='comentario',
            field=models.TextField(verbose_name='Tu Comentario'),
        ),
        migrations.AlterField(
            model_name='resena',
            name='estrellas',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5, verbose_name='Calificación'),
        ),
        migrations.AlterField(
            model_name='resena',
            name='nombre_cliente',
            field=models.CharField(max_length=100, verbose_name='Tu Nombre'),
        ),
    ]
