# Generated by Django 6.0.4 on 2026-04-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_resena_options_alter_resena_comentario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('recibido', '📝 Recibido'), ('preparando', '👩\u200d🍳 En Preparación'), ('listo', '🛍️ Listo / En Camino'), ('entregado', '✅ Entregado')], default='recibido', max_length=20),
        ),
    ]
