# Generated by Django 6.0.4 on 2026-04-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_orden_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='fecha_retiro',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Retiro'),
        ),
    ]
