# Generated by Django 6.0.4 on 2026-04-14 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_orden_fecha_retiro'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenActiva',
            fields=[
            ],
            options={
                'verbose_name': 'Orden Pendiente',
                'verbose_name_plural': '📦 Órdenes Pendientes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.orden',),
        ),
        migrations.CreateModel(
            name='OrdenHistorial',
            fields=[
            ],
            options={
                'verbose_name': 'Orden Finalizada',
                'verbose_name_plural': '📜 Historial de Órdenes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.orden',),
        ),
    ]
